#server:
#   port: 8444
#   ssl:
#       enabled: true
#       client-auth: need
#       key-store: classpath:user-regis-api-cert.jks
#       key-store-password: India330$$
#       keyStoreType: JKS
#       keyStoreProvider: SUN
#       keyAlias: user-regis-api-cert
#       trust-store: classpath:user-regis-api-cert.jks
#       trust-store-password: India330$$
#       trust-store-type: JKS
eureka:
# instance:
#   nonSecurePortEnabled: false
#    securePortEnabled: true
#    securePort: ${server.port}
#    statusPageUrl: https://localhost:${server.port}/info
#    healthCheckUrl: https://localhost:${server.port}/health
#    homePageUrl: https://localhost:${server.port}
  client:
#    securePortEnabled: true
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#when deployed on tomcat
       defaultZone: http://localhost:8080/spring-discovery-service-war/eureka
      
spring:
  jta:
    atomikos:
      properties:
        max-timeout: 900000